
#Script to calculate median number of genes per sample (after final filtering).
library(Seurat)

scRNA_seq_expt <- readRDS("../RDS_files/seuratObject_rename_ident_May26_2021.rds")
sc_obj <- SplitObject(scRNA_seq_expt, split.by = "replicate")

summary(sc_obj$M3_rep1$nFeature_RNA)
summary(sc_obj$M3_rep2$nFeature_RNA)
summary(sc_obj$M3_rep3$nFeature_RNA)
summary(sc_obj$M3_rep4$nFeature_RNA)
summary(sc_obj$M3_rep5$nFeature_RNA)
summary(sc_obj$M3_rep6$nFeature_RNA)
summary(sc_obj$M18_rep1$nFeature_RNA)
summary(sc_obj$M18_rep2$nFeature_RNA)
summary(sc_obj$M18_rep3$nFeature_RNA)
summary(sc_obj$M18_rep4$nFeature_RNA)
summary(sc_obj$M18_rep5$nFeature_RNA)
summary(sc_obj$M18_rep6$nFeature_RNA)

max(sc_obj$M3_rep1$nFeature_RNA)
max(sc_obj$M3_rep2$nFeature_RNA)
max(sc_obj$M3_rep3$nFeature_RNA)
max(sc_obj$M3_rep4$nFeature_RNA)
max(sc_obj$M3_rep5$nFeature_RNA)
max(sc_obj$M3_rep6$nFeature_RNA)
max(sc_obj$M18_rep1$nFeature_RNA)
max(sc_obj$M18_rep2$nFeature_RNA)
max(sc_obj$M18_rep3$nFeature_RNA)
max(sc_obj$M18_rep4$nFeature_RNA)
max(sc_obj$M18_rep5$nFeature_RNA)
max(sc_obj$M18_rep6$nFeature_RNA)

median(sc_obj$M3_rep1$nFeature_RNA)
median(sc_obj$M3_rep2$nFeature_RNA)
median(sc_obj$M3_rep3$nFeature_RNA)
median(sc_obj$M3_rep4$nFeature_RNA)
median(sc_obj$M3_rep5$nFeature_RNA)
median(sc_obj$M3_rep6$nFeature_RNA)
median(sc_obj$M18_rep1$nFeature_RNA)
median(sc_obj$M18_rep2$nFeature_RNA)
median(sc_obj$M18_rep3$nFeature_RNA)
median(sc_obj$M18_rep4$nFeature_RNA)
median(sc_obj$M18_rep5$nFeature_RNA)
median(sc_obj$M18_rep6$nFeature_RNA)

